# Generated by Django 3.2.18 on 2023-03-18 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='UserAcct',
            name='middle_name',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
