# Generated by Django 3.2.18 on 2023-03-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useracct_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracct',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
