# Generated by Django 3.2.18 on 2023-03-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
