# Generated by Django 3.2.18 on 2023-03-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
