# Generated by Django 3.2.18 on 2023-03-23 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasks_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='title',
        ),
    ]
